spring:
  datasource:
    url: jdbc:mysql://wanglinli955.cn:3306/centosafe
    username: root
    password: wy955955
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update